### ISSUE TITLE
Pan Gesture basic example wrong behaviour

### ISSUE THREAD

**Issue by Vladis92** [C4Labs/C4iOS#683]
I'm trying to replicate the basic example of dragging a shape with the UIPanGestureRecognizer.

This is my code:

```
import UIKit
import C4

class C4ViewController: CanvasController {
    
    override func setup() {
        let square = Rectangle(frame: Rect(0,0,100,100))
        square.center = canvas.center
        self.canvas.add(square)
        
        
        square.addPanGestureRecognizer{ location, center, translation, velocity, state in
            square.center = center
  
        }
        
    }
}
```

This is the behaviour I get:
https://vid.me/GjKx

I also get a warning "Result of call to 'addPanGestureRecognizer' is unused"
Using version C4 2.0.0 with Xcode 8.0 and Swift 3

**Comment by C4Framework** [comment]
Got it. 

You should do this: 

```
square.addPanGestureRecognizer { locations, center, translation, velocity, state in
    let p = self.canvas.convert(center, from: square)
    square.center = p
}
```

The demo attaches the gesture to the canvas. However, you're attaching the gesture to the shape itself, which causes the flicker because of this:

1. your touch starts in the center of the shape `{50,50}`
2. `square.center = center` sets the shape's actual center to `{50, 50}`
3. your touch doesn't move relative to the canvas, and...
3. your touch is now at a relative point **outside** the shape, let's say ~`{200,200}`
4. `square.center = center` sets the shape's center to ~`{200,200}`
5. your touch is now in the shape again, and measured relative to the shape's top-right corner
6. `square.center = center` sets the shape's actual center to ~`{50, 50}`
7. repeat...

**Comment by C4Framework** [comment]
The warning you get is something that comes with Xcode8, we get it too... Doesn't seem to affect anything.
